### ISSUE TITLE
Issue with the symbol image padding and button alignment on larger screens

### ISSUE THREAD

**Issue by JiffyBees** [JiffyBees/modularity-mindfulness#2]
I have been trying to push the symbol image down a little bit for the 608px screen size and adjust the buttons so there lined up next to one another. I have been able to make a lot of small fixes to my code but I can't figure these last two things out.
@charlie-quinn

**Comment by charlie-quinn** [comment]
@JiffyBees please provide a screenshot regarding ☝️

**Comment by JiffyBees** [comment]
[image: Markbot.png]
[image: Markbot 2.png]
these are Markbots examples above

and below are my issues,  I am having a hard time lining up my buttons and
fixing this spacing on the image.
[image: my example 2.png]
[image: Screen Shot 2019-09-16 at 11.51.21 AM.png]

@charlie-quinn

**Comment by JiffyBees** [comment]
I don't know if you can see these images I just sent, I am still not used to the git hub issues.
@charlie-quinn
